### ISSUE TITLE
POI wrong position adjustment on the map

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#55]
**Description:**
POI aren't correctly positionned on the map at the app lauch

**Steps to reproduce:**
1. POI are already refreshed in the app
2. Close and re-open the app

**Behaviour**
POI aren't correctly positionned on the map (I know the positions)
Then I use the zoom. When I reach the 18 zoom level, POI go to their exact position

**Environment:**
Smartphone : Wiko Rainbow 4G – Android 4.4.2

**Version:**
3.0.0-beta1 (2016-08-22) + "Preset par défaut" profile
I update the 2.2 version with the new one.

**Comment by Hugoo13** [comment]
Hi @GilBr, thank you for reaching out !

This is a known issue. We use Mapbox to display the map, and this issue is related to Mapbox.
We already report the [problem](https://github.com/mapbox/mapbox-gl-native/issues/5604) on [Mapbox's Github](https://github.com/mapbox/mapbox-gl-native).

We will inform you when the problem will be solved.

**Comment by loicortola** [comment]
Added screenshots to better explain the problem:
![dy1zbnaa](https://cloud.githubusercontent.com/assets/2526081/17924832/9ecd30ae-69ea-11e6-8606-3195f0971040.jpg)
![vea2qywr](https://cloud.githubusercontent.com/assets/2526081/17924831/9ecc3cb2-69ea-11e6-8ae3-d5ef5e199374.jpg)

**Comment by Hugoo13** [comment]
Should be fixed in next release ! Stay tuned !
