### ISSUE TITLE
Get your app in the F-Droid store, or at least provide a .apk download

### ISSUE THREAD

**Issue by de-vries** [jawg/osm-contributor#76]
I'd like to try your app, but I'm one of those people that refuses to install google services. 
I found [one source](https://apkplz.com/android-apps/osm-contributor/osm-contributor-3-0-1) that offers a .apk, but I not sure if I should trust this source and the apk I downloaded didn't install.

Can you please get your app in the F-Droid store, or at least provide a .apk download?

**Comment by stephan75** [comment]
Did you try the apk files directly from this repo?

https://github.com/jawg/osm-contributor/releases

**Comment by de-vries** [comment]
that looks more trustworthy, and the apk installs. Thanks a lot!

**Comment by loicortola** [comment]
Hi @de-vries , Thanks @stephan75 

@de-vries , we tried the F-Droid for a previous release, but it requires us to take off our analytics library which is not Opensource (fabric.io). This was a pain since we could not get any crash reports from those.

Therefore, the official APK (signed) is exposed on our repository as mentioned by Stephan.

Hope you find the app as cool as we tried to make it look :)

**Comment by juliencarnot** [comment]
Did you consider using an open-source alternative such as https://github.com/Countly ?

**Comment by IzzySoft** [comment]
The request for F-Droid inclusion was now open for 1.5 years and is still stalled as there is no FOSS flavor available. F-Droid needs to build completely from source, and all components need to be free and open source – which is not the case if things like Crashlytics are included. There are open source analytic frameworks if you insist to need such a thing. There's Countly Julien mentioned, there's [ACRA](https://github.com/ACRA/acra), there are certainly others.

But as long as this requirement is not fulfilled, the app cannot be made available at F-Droid. It's a real pity that, to contribute to a FOSS project (OSM,) one is bound to proprietary components just for analytic purposes. This makes the app look tainted to FOSS enthusiasts.

Other issues have been mentioned in #1 #166 #169 and probably other issues I've missed, at least since 2015. The issue at F-Droid is stalled since 2017. You already wrote your app should urgently focus on getting to F-Droid. But still, it looks like this is getting nowhere. Hence I've now closed the [RFP at F-Droid](https://gitlab.com/fdroid/rfp/issues/358). Should you finally decide on doing something about it, please let us know – we gladly reopen the RFP anytime if we see it can be processed.

PS: Apologies if I sounded harsh; I'm just disappointed for the current state.
